# Generated by Django 3.0.5 on 2022-04-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20200430_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAndPurchasesHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
