# Generated by Django 3.0.5 on 2022-04-25 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_auto_20220423_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingandpurchaseshistory',
            name='timing',
            field=models.CharField(choices=[('1', '1PM - 2PM'), ('2', '2PM - 3PM'), ('3', 'Sharks'), ('4', '3PM - 4PM')], default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='first_team_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='second_team_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=256, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
