# Generated by Django 3.0.5 on 2022-04-25 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_auto_20220425_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingandpurchaseshistory',
            old_name='timing',
            new_name='timings',
        ),
    ]
