# Generated by Django 3.0.5 on 2022-04-25 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_auto_20220425_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=256, validators=[django.core.validators.RegexValidator('^([a-zA-Z]+\\s)*[a-zA-Z]+$', 'Only characters are allowed.')]),
        ),
    ]
