# Generated by Django 3.0.5 on 2022-04-25 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_auto_20220425_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingandpurchaseshistory',
            old_name='made_on',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='bookingandpurchaseshistory',
            old_name='fields',
            new_name='Fields',
        ),
        migrations.RenameField(
            model_name='bookingandpurchaseshistory',
            old_name='timings',
            new_name='Timing',
        ),
    ]
