# Generated by Django 3.0.5 on 2022-04-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0019_auto_20220425_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Newsletter',
            },
        ),
        migrations.CreateModel(
            name='TeamFormationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GK_SP', models.CharField(max_length=255)),
                ('DF_SP_L', models.CharField(max_length=255)),
                ('DF_SP_LM', models.CharField(max_length=255)),
                ('DF_SP_RM', models.CharField(max_length=255)),
                ('DF_SP_R', models.CharField(max_length=255)),
                ('MF_SP_L', models.CharField(max_length=255)),
                ('MF_SP_LM', models.CharField(max_length=255)),
                ('MF_SP_RM', models.CharField(max_length=255)),
                ('MF_SP_R', models.CharField(max_length=255)),
                ('FW_SP_LW', models.CharField(max_length=255)),
                ('FW_SP_RW', models.CharField(max_length=255)),
                ('GK_NS', models.CharField(max_length=255)),
                ('DF_NS_1', models.CharField(max_length=255)),
                ('DF_NS_2', models.CharField(max_length=255)),
                ('MF_NS_1', models.CharField(max_length=255)),
                ('MF_NS_2', models.CharField(max_length=255)),
                ('FW_NS_LW', models.CharField(max_length=255)),
                ('FW_NS_RW', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Team Formation',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=255)),
                ('homeTeam', models.CharField(max_length=255)),
                ('awayTeam', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.AlterField(
            model_name='consultation',
            name='coach_name',
            field=models.CharField(choices=[('1', 'Youssef El Sayed'), ('2', 'Karim Nasreddine'), ('3', 'Jad Jawad'), ('4', 'Yasmina Mehshi'), ('5', 'Salwa Fidawi')], default=None, max_length=256),
        ),
    ]
