# Generated by Django 3.0.5 on 2022-04-27 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0020_auto_20220427_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingandpurchaseshistory',
            options={'verbose_name_plural': 'Booking and Purchases History'},
        ),
        migrations.RemoveField(
            model_name='bookingandpurchaseshistory',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='bookingandpurchaseshistory',
            name='Fields',
        ),
        migrations.RemoveField(
            model_name='bookingandpurchaseshistory',
            name='Timing',
        ),
        migrations.AddField(
            model_name='bookingandpurchaseshistory',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingandpurchaseshistory',
            name='time',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
