# Generated by Django 3.0.5 on 2022-04-28 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0024_auto_20220427_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name_plural': 'Upcoming Games'},
        ),
    ]
