# Generated by Django 3.2.13 on 2022-04-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='name',
            new_name='first',
        ),
    ]
