# Generated by Django 3.2.13 on 2022-04-20 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_rename_name_consultation_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='startdate',
            field=models.DateField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
