# Generated by Django 3.2.13 on 2022-04-20 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_rename_startdate_consultation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
