# Generated by Django 3.2.13 on 2022-04-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0005_consultation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_re', models.CharField(max_length=100)),
                ('email_re', models.CharField(max_length=100)),
                ('start_date', models.DateField(max_length=100)),
                ('end_date', models.DateField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='number',
        ),
        migrations.AlterField(
            model_name='consultation',
            name='date',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='first',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='time',
            field=models.TimeField(max_length=100),
        ),
    ]
