# Generated by Django 3.2.13 on 2022-04-21 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0006_auto_20220421_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='number',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='number_re',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
