# Generated by Django 3.2.13 on 2022-04-23 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0007_auto_20220421_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='coach',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.CharField(max_length=100),
        ),
    ]
