# Generated by Django 3.2.13 on 2022-04-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0008_auto_20220423_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='coach',
            new_name='coach_name',
        ),
    ]
