# Generated by Django 3.2.13 on 2022-04-23 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0009_rename_coach_consultation_coach_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='first',
            new_name='name_1',
        ),
    ]
