# Generated by Django 3.2.13 on 2022-04-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0010_rename_first_consultation_name_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
