# Generated by Django 3.2.13 on 2022-04-23 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0011_alter_consultation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='name_1',
            new_name='name_consultation',
        ),
    ]
