# Generated by Django 3.2.13 on 2022-04-23 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0012_rename_name_1_consultation_name_consultation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='name_consultation',
            new_name='name_1',
        ),
    ]
