# Generated by Django 3.2.13 on 2022-04-23 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0013_rename_name_consultation_consultation_name_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='email_re',
            new_name='email_reservation',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='name_re',
            new_name='name_reservation',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='number_re',
            new_name='number_reservation',
        ),
    ]
