# Generated by Django 4.0.3 on 2022-04-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=255)),
                ('homeTeam', models.CharField(max_length=255)),
                ('awayTeam', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Teams',
            },
        ),
    ]
