# Generated by Django 4.0.3 on 2022-04-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eaglesFC', '0003_teamformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Newsletter',
            },
        ),
    ]
