# Generated by Django 4.0.3 on 2022-04-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eaglesFC', '0004_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamFormationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GK_SP', models.CharField(max_length=255)),
                ('DF_SP_L', models.CharField(max_length=255)),
                ('DF_SP_LM', models.CharField(max_length=255)),
                ('DF_SP_RM', models.CharField(max_length=255)),
                ('DF_SP_R', models.CharField(max_length=255)),
                ('MF_SP_L', models.CharField(max_length=255)),
                ('MF_SP_LM', models.CharField(max_length=255)),
                ('MF_SP_RM', models.CharField(max_length=255)),
                ('MF_SP_R', models.CharField(max_length=255)),
                ('FW_SP_LW', models.CharField(max_length=255)),
                ('FW_SP_RW', models.CharField(max_length=255)),
                ('GK_NS', models.CharField(max_length=255)),
                ('DF_NS_1', models.CharField(max_length=255)),
                ('DF_NS_2', models.CharField(max_length=255)),
                ('MF_NS_1', models.CharField(max_length=255)),
                ('MF_NS_2', models.CharField(max_length=255)),
                ('FW_NS_LW', models.CharField(max_length=255)),
                ('FW_NS_RW', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Team Formation',
            },
        ),
        migrations.DeleteModel(
            name='TeamFormation',
        ),
    ]
