# Generated by Django 4.0.3 on 2022-04-13 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eaglesFC', '0005_teamformationmodel_delete_teamformation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamFormationModel',
        ),
    ]
