# Generated by Django 4.0.4 on 2022-04-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eaglesFC', '0008_alter_teams_awayteam_alter_teams_hometeam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='awayTeam',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teams',
            name='homeTeam',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teams',
            name='time',
            field=models.CharField(max_length=255),
        ),
    ]
